- name: Stop Nginx service
  service:
    name: nginx
    state: stopped
  ignore_errors: true

- name: Disable Nginx service
  service:
    name: nginx
    enabled: no
  ignore_errors: true

- name: Uninstall nginx and related packages
  apt:
    name:
      - nginx
      - nginx-common
      - nginx-full
    state: absent
    purge: yes
    update_cache: yes

- name: Remove Nginx configuration and log directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx
    - /var/log/nginx
    - /var/www/html
  ignore_errors: true